### ISSUE TITLE
Errors in the installation of ns3-ai

### ISSUE THREAD

**Issue by Pangeensi** [hust-diangroup/ns3-ai#10]
I tried to install the release version of ns3-ai into ns3-3.31 following README guidance, but some errors occurred.

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing ns3_ai.egg-info/PKG-INFO
writing top-level names to ns3_ai.egg-info/top_level.txt
writing dependency_links to ns3_ai.egg-info/dependency_links.txt
reading manifest file 'ns3_ai.egg-info/SOURCES.txt'
writing manifest file 'ns3_ai.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'shm_pool' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kjnyAR/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c memory-pool.c -o build/temp.linux-x86_64-2.7/memory-pool.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kjnyAR/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c memory-pool-module.c -o build/temp.linux-x86_64-2.7/memory-pool-module.o
memory-pool-module.c:79:15: error: variable ‘shmModule’ has initializer but incomplete type
 static struct PyModuleDef shmModule = {
               ^~~~~~~~~~~
memory-pool-module.c:80:5: error: ‘PyModuleDef_HEAD_INIT’ undeclared here (not in a function); did you mean ‘PyObject_HEAD_INIT’?
     PyModuleDef_HEAD_INIT,
     ^~~~~~~~~~~~~~~~~~~~~
     PyObject_HEAD_INIT
memory-pool-module.c:80:5: warning: excess elements in struct initializer
memory-pool-module.c:80:5: note: (near initialization for ‘shmModule’)
memory-pool-module.c:81:5: warning: excess elements in struct initializer
     "shm_pool",           /* name of module */
     ^~~~~~~~~~
memory-pool-module.c:81:5: note: (near initialization for ‘shmModule’)
memory-pool-module.c:82:5: warning: excess elements in struct initializer
     "Shared memory pool", /* Doc string (may be NULL) */
     ^~~~~~~~~~~~~~~~~~~~
memory-pool-module.c:82:5: note: (near initialization for ‘shmModule’)
memory-pool-module.c:83:5: warning: excess elements in struct initializer
     -1,                   /* Size of per-interpreter state or -1 */
     ^
memory-pool-module.c:83:5: note: (near initialization for ‘shmModule’)
memory-pool-module.c:84:5: warning: excess elements in struct initializer
     MemoryPool_methods    /* Method table */
     ^~~~~~~~~~~~~~~~~~
memory-pool-module.c:84:5: note: (near initialization for ‘shmModule’)
memory-pool-module.c: In function ‘PyInit_shm_pool’:
memory-pool-module.c:91:12: warning: implicit declaration of function ‘PyModule_Create’; did you mean ‘_PyModule_Clear’? [-Wimplicit-function-declaration]
     return PyModule_Create(&shmModule);
            ^~~~~~~~~~~~~~~
            _PyModule_Clear
memory-pool-module.c:91:12: warning: ‘return’ with a value, in function returning void
     return PyModule_Create(&shmModule);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
memory-pool-module.c:89:1: note: declared here
 PyInit_shm_pool(void)
 ^~~~~~~~~~~~~~~
memory-pool-module.c: At top level:
memory-pool-module.c:79:27: error: storage size of ‘shmModule’ isn’t known
 static struct PyModuleDef shmModule = {
                           ^~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

Is it that I didn't install it in a fixed version? ns-3.30 is no longer installable because of the update of gcc and g++.  Are there any other solutions？

**Comment by Pangeensi** [comment]
The errors occurred in the step of  "python setup.py install --user"

**Comment by eiclpy** [comment]
Python 2 is about to stop supporting, you can try Python 3.
use "python3 setup.py install --user" or "pip3 install . --user"
