### ISSUE TITLE
Installing on ns3.29

### ISSUE THREAD

**Issue by mtahrawi** [hust-diangroup/ns3-ai#13]
Hi all,
can I install your work on ns3-39. Please can be more explanation and any tutorial about the implementation. I read your paper entitled **"NS3-AI: Enable Applying Artificial Intelligence to Network Simulation in ns-3**", but I am still confusing.
Thanks.

**Comment by mtahrawi** [comment]
no comment!

**Comment by Mauriyin** [comment]
Currently, the ns3-ai is aligned with ns3.31, we plan to test more on different versions and provide more instructions later.

Our model is based on the shared memory structure to enable the data transfer between the ns-3 and AI frameworks. So you have some knowledge in the shared memory structure that could be helpful.

Could you be more specific about what part that makes you confused? It's a little bit hard for us to explain without any specific problems.
