### ISSUE TITLE
After completing the ns3-ai installation, there is an error in executing the command "./waf --run "rl-tcp" according to the reference process. What is the reason?

### ISSUE THREAD

**Issue by nostalgia1995** [hust-diangroup/ns3-ai#14]
In file included from ../scratch/rl-tcp/tcp-rl.h:7:0,
                 from ../scratch/rl-tcp/sim.cc:20:
../scratch/rl-tcp/tcp-rl-env.h:54:74: error: ‘TcpCAEvent_t’ in ‘class ns3::TcpSocketState’ does not name a type
   virtual void CwndEvent (Ptr<TcpSocketState> tcb, const TcpSocketState::TcpCAEvent_t event) = 0;
                                                                          ^~~~~~~~~~~~
../scratch/rl-tcp/tcp-rl-env.h:122:74: error: ‘TcpCAEvent_t’ in ‘class ns3::TcpSocketState’ does not name a type
   virtual void CwndEvent (Ptr<TcpSocketState> tcb, const TcpSocketState::TcpCAEvent_t event);
                                                                          ^~~~~~~~~~~~
In file included from ../scratch/rl-tcp/sim.cc:20:0:
../scratch/rl-tcp/tcp-rl.h:96:74: error: ‘TcpCAEvent_t’ in ‘class ns3::TcpSocketState’ does not name a type
   virtual void CwndEvent (Ptr<TcpSocketState> tcb, const TcpSocketState::TcpCAEvent_t event);
                                                                          ^~~~~~~~~~~~
../scratch/rl-tcp/sim.cc: In function ‘int main(int, char**)’:
../scratch/rl-tcp/sim.cc:199:50: error: ‘QueueSizeUnit’ has not been declared
                       QueueSizeValue (QueueSize (QueueSizeUnit::PACKETS, size / mtu_bytes)));
                                                  ^~~~~~~~~~~~~
../scratch/rl-tcp/sim.cc:199:90: error: ‘QueueSize’ was not declared in this scope
                       QueueSizeValue (QueueSize (QueueSizeUnit::PACKETS, size / mtu_bytes)));
                                                                                          ^
../scratch/rl-tcp/sim.cc:199:91: error: ‘QueueSizeValue’ was not declared in this scope
                       QueueSizeValue (QueueSize (QueueSizeUnit::PACKETS, size / mtu_bytes)));
                                                                                           ^
../scratch/rl-tcp/sim.cc:201:50: error: ‘QueueSizeUnit’ has not been declared
                       QueueSizeValue (QueueSize (QueueSizeUnit::BYTES, size)));
                                                  ^~~~~~~~~~~~~

In file included from ../scratch/rl-tcp/tcp-rl-env.cc:2:0:
../scratch/rl-tcp/tcp-rl-env.h:54:74: error: ‘TcpCAEvent_t’ in ‘class ns3::TcpSocketState’ does not name a type
   virtual void CwndEvent (Ptr<TcpSocketState> tcb, const TcpSocketState::TcpCAEvent_t event) = 0;
                                                                          ^~~~~~~~~~~~
../scratch/rl-tcp/tcp-rl-env.h:122:74: error: ‘TcpCAEvent_t’ in ‘class ns3::TcpSocketState’ does not name a type
   virtual void CwndEvent (Ptr<TcpSocketState> tcb, const TcpSocketState::TcpCAEvent_t event);
                                                                          ^~~~~~~~~~~~
../scratch/rl-tcp/tcp-rl-env.cc: In member function ‘virtual void ns3::TcpTimeStepEnv::IncreaseWindow(ns3::Ptr<ns3::TcpSocketState>, uint32_t)’:
../scratch/rl-tcp/tcp-rl-env.cc:236:34: error: ‘class ns3::TcpSocketState’ has no member named ‘m_bytesInFlight’
   m_bytesInFlight.push_back(tcb->m_bytesInFlight);
                                  ^~~~~~~~~~~~~~~
../scratch/rl-tcp/tcp-rl-env.cc: At global scope:
../scratch/rl-tcp/tcp-rl-env.cc:266:79: error: ‘TcpCAEvent_t’ in ‘class ns3::TcpSocketState’ does not name a type
 void TcpTimeStepEnv::CwndEvent(Ptr<TcpSocketState> tcb, const TcpSocketState::TcpCAEvent_t event)
                                                                               ^~~~~~~~~~~~

In file included from ../scratch/rl-tcp/tcp-rl.h:7:0,
                 from ../scratch/rl-tcp/tcp-rl.cc:1:
../scratch/rl-tcp/tcp-rl-env.h:54:74: error: ‘TcpCAEvent_t’ in ‘class ns3::TcpSocketState’ does not name a type
   virtual void CwndEvent (Ptr<TcpSocketState> tcb, const TcpSocketState::TcpCAEvent_t event) = 0;
                                                                          ^~~~~~~~~~~~
../scratch/rl-tcp/tcp-rl-env.h:122:74: error: ‘TcpCAEvent_t’ in ‘class ns3::TcpSocketState’ does not name a type
   virtual void CwndEvent (Ptr<TcpSocketState> tcb, const TcpSocketState::TcpCAEvent_t event);
                                                                          ^~~~~~~~~~~~
In file included from ../scratch/rl-tcp/tcp-rl.cc:1:0:
../scratch/rl-tcp/tcp-rl.h:96:74: error: ‘TcpCAEvent_t’ in ‘class ns3::TcpSocketState’ does not name a type
   virtual void CwndEvent (Ptr<TcpSocketState> tcb, const TcpSocketState::TcpCAEvent_t event);
                                                                          ^~~~~~~~~~~~
../scratch/rl-tcp/tcp-rl.cc:221:75: error: ‘TcpCAEvent_t’ in ‘class ns3::TcpSocketState’ does not name a type
 TcpRlTimeBased::CwndEvent (Ptr<TcpSocketState> tcb, const TcpSocketState::TcpCAEvent_t event)
                                                                           ^~~~~~~~~~~~

Waf: Leaving directory `/media/nostalgia/Document/Deepin File/software/NS3/ns-allinone-3.26/ns-3.26/build'
Build failed
 -> task in 'rl-tcp' failed (exit status 1): 
	{task 140333546644944: cxx sim.cc -> sim.cc.5.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-std=c++11', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/libpng16', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_=1', '-DHAVE_GSL=1', '-DHAVE_SQLITE3=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '../scratch/rl-tcp/sim.cc', '-c', '-o', '/media/nostalgia/Document/Deepin File/software/NS3/ns-allinone-3.26/ns-3.26/build/scratch/rl-tcp/sim.cc.5.o']
 -> task in 'rl-tcp' failed (exit status 1): 
	{task 140333546645072: cxx tcp-rl-env.cc -> tcp-rl-env.cc.5.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-std=c++11', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/libpng16', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_=1', '-DHAVE_GSL=1', '-DHAVE_SQLITE3=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '../scratch/rl-tcp/tcp-rl-env.cc', '-c', '-o', '/media/nostalgia/Document/Deepin File/software/NS3/ns-allinone-3.26/ns-3.26/build/scratch/rl-tcp/tcp-rl-env.cc.5.o']
 -> task in 'rl-tcp' failed (exit status 1): 
	{task 140333546645200: cxx tcp-rl.cc -> tcp-rl.cc.5.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-std=c++11', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/libpng16', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_=1', '-DHAVE_GSL=1', '-DHAVE_SQLITE3=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '../scratch/rl-tcp/tcp-rl.cc', '-c', '-o', '/media/nostalgia/Document/Deepin File/software/NS3/ns-allinone-3.26/ns-3.26/build/scratch/rl-tcp/tcp-rl.cc.5.o']

**Comment by Mauriyin** [comment]
Could you provide more details about the ns-3 versions you are using?
