### ISSUE TITLE
AttributeError: module 'py_interface' has no attribute 'Init'

### ISSUE THREAD

**Issue by tahminehjavadzadeh** [hust-diangroup/ns3-ai#15]
Hello,
when I run the rl-tcp example in the python part: "python3 testtcp.py", I get the following error:

Traceback (most recent call last):
  File "testtcp.py", line 28, in <module>
    py_interface.Init(1234, 4096)
AttributeError: module 'py_interface' has no attribute 'Init'

Regards,

**Comment by tahminehjavadzadeh** [comment]
> Hello,
> when I run the rl-tcp example in the python part: "python3 testtcp.py", I get the following error:
> 
> Traceback (most recent call last):
> File "testtcp.py", line 28, in
> py_interface.Init(1234, 4096)
> AttributeError: module 'py_interface' has no attribute 'Init'
> 
> Regards,

Also, I recognized that in ns3 part, after running: ./waf --run "rl-tcp" , createEnv is not successful and the result is:
--seed: 0
--Tcp version: ns3::TcpRlTimeBased
CreateEnv0
CreateEnv0

**Comment by Mauriyin** [comment]
Solution:

Add the path installed into the environment path:
```
export PYTHONPATH=/home/xxx/.local/lib/python3.x/site-packages/ns3_ai-0.0.2-py3.x-linux-x86_64.egg:$ PYTHONPATH
```

**Comment by tahminehjavadzadeh** [comment]
> Solution:
> 
> Add the path installed into the environment path:
> 
> ```
> export PYTHONPATH=/home/xxx/.local/lib/python3.x/site-packages/ns3_ai-0.0.2-py3.x-linux-x86_64.egg:$ PYTHONPATH
> ```

Thank you,

**Comment by litmyp** [comment]
去site-packages下面检查一下你的py_interface是不是装成了"py_interface:Erlang 到 Python 的集成"这个重名库
