### ISSUE TITLE
Error when run CQI example

### ISSUE THREAD

**Issue by mtahrawi** [hust-diangroup/ns3-ai#17]
Hi developers,
Thanks for this great jop, when I try to run CQI example, this encounter error is raised
/home/ns3/.local/lib/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars    ret = ret.dtype.type(ret / rcount)"
can help me to settle this issue.
Tq

**Comment by Mauriyin** [comment]
Could you provide more details like which machine you are using? Also, can you show the full error logs to help to locate the problems?
