### ISSUE TITLE
Cite ns3-ai in the model of ns3

### ISSUE THREAD

**Issue by nostalgia1995** [hust-diangroup/ns3-ai#22]
Excuse me, what's the reason about the phenomenon in the image when I cite ns3-Ai in a model of ns3?
![bug](https://user-images.githubusercontent.com/56420636/114267097-82491c00-9a2c-11eb-86f6-2089e9dedf4f.png)

**Comment by Mauriyin** [comment]
It seems like you need to add ns3-ai to wscript in your model.  
You need find src/YOURMODEL/wscript  and add ns3-ai into the dependencies.
For example, if you want to add the ns3-ai to LTE model, you should change this line to add ns3-ai:
```
lte_module_dependencies = ['core', 'network', 'spectrum', 'stats', 'buildings', 'virtual-net-device','point-to-point','applications','internet','csma','ns3-ai']
```

**Comment by nostalgia1995** [comment]
well, the issue resolved by your way. Thanks so much!
