### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by llllllllluGquan** [hust-diangroup/ns3-ai#23]
Hi,
I follow the readme to install the ns3-ai,.But when I execute the command './waf', he told me "Could not find a task generator for the name 'ns3-ns3-ai-master' ". The version I used is ns-3.32. Thank you!

**Comment by Mauriyin** [comment]
What's your folder name for the ns3-ai module?

**Comment by llllllllluGquan** [comment]
> What's your folder name for the ns3-ai module?

I got it, thanks. But it occurs a error: No module named 'py_interface'.

**Comment by Mauriyin** [comment]
You need to install the py_interface first as shown [here](https://github.com/hust-diangroup/ns3-ai/tree/master/py_interface#install). If still having issues, you can check if there is some environment path issue like [here](https://github.com/hust-diangroup/ns3-ai/issues/15)

**Comment by llllllllluGquan** [comment]
Thank you very much! I want to run the benchmark congestion control, for example, cubic ,vegas and so on.  I used the ns3 the version I downloaded from the ooficial website.  In folder "rl-tcp", when I change the congestion control protocol, such as, from TCP NewReno to Vegas. But it didn't work. So can i ask you something about this? Thanks again!!!
