### ISSUE TITLE
'run_online_lstm.py' is not compatible with the newest releases of TensorFlow and Keras

### ISSUE THREAD

**Issue by ahmadnagib** [hust-diangroup/ns3-ai#3]
The `tf.set_random_seed()` function in https://github.com/hust-diangroup/ns3-ai/blob/2eac6215623b43075ad3a35c30581456e85ea350/example/lte_cqi/run_online_lstm.py#L55
is no longer supported by TensorFlow's latest release, and it is currently replaced by [`tf.random.set_seed()` ](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

Additionally, Keras newest release only supports TensorFlow 2.2 or higher.

I had to revert back to TensorFlow 1.15.3 and Keras 2.3.0 to be able to resolve this issue. It would be great if you could update the code to accommodate for such changes or at least mention the TensorFlow and Keras releases that you originally used to run the code.

**Comment by Mauriyin** [comment]
Fixed with commit #12
