### ISSUE TITLE
Issue when re-running the simulation with same memblock_key

### ISSUE THREAD

**Issue by sbhTWR** [hust-diangroup/ns3-ai#34]
Hello,
I have installed ns3-ai and running it with my simulation setup successfully. However, it breaks and exits when I run the same setup second time with the **same** 'memblock_key'. I am using the template provided [here](https://github.com/hust-diangroup/ns3-ai/blob/master/example/lte_cqi/run_online.py). It works, but if I run it second time, it breaks at the following line:
````
if data == None:    
    break
`````
To run the setup again, I have to change the 'memblock_key' to some other value and then it starts working again. Is there some cleanup task that needs to be done before exiting the script?
Thanks

**Comment by Mauriyin** [comment]
Yes. You can use this [script](https://github.com/hust-diangroup/ns3-ai/blob/master/freeshm.sh) to clean up memory.

**Comment by sbhTWR** [comment]
Thanks that works.
