### ISSUE TITLE
'run_online_lstm.py': NameError: name 'K' is not defined

### ISSUE THREAD

**Issue by ahmadnagib** [hust-diangroup/ns3-ai#4]
After resolving the issue mention in #3, the following line results in the error highlighted below: https://github.com/hust-diangroup/ns3-ai/blob/2eac6215623b43075ad3a35c30581456e85ea350/example/lte_cqi/run_online_lstm.py#L68

`Traceback (most recent call last):
  File "run_online_lstm.py", line 69, in <module>
    lstm_l1_mse = Lambda(my_dense)(lstm_input_vec)
  File "/home/ahmadnagib/anaconda3/envs/py37/lib/python3.7/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/ahmadnagib/anaconda3/envs/py37/lib/python3.7/site-packages/keras/layers/core.py", line 716, in call
    return self.function(inputs, **arguments)
  File "run_online_lstm.py", line 68, in my_dense
    return K.expand_dims(Dense(30, activation='selu', kernel_regularizer='l1', )(x[:, :, 0]), axis=-1)
NameError: name 'K' is not defined
`

Note: Tested on a Ubuntu 20.04 via Anaconda Prompt with Python 3.7.7, TensorFlow 1.15.3 and Keras 2.3.0

**Comment by Mauriyin** [comment]
Could you try to add the code below and test again?
`import keras.backend as K`.

**Comment by ahmadnagib** [comment]
> Could you try to add the code below and test again?
> `import keras.backend as K`.

I gave it a try and it seems to solve the issue, but there are other issues that prevent the script from running properly, most probably because the versions of TensorFlow and Keras that I am using are different from the ones you used.

Here is what I get:

`Using TensorFlow backend.
WARNING:tensorflow:From run_online_lstm.py:56: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.
WARNING:tensorflow:From /home/ahmadnagib/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /home/ahmadnagib/anaconda3/envs/py37/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3313: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
run_online_lstm.py:80: RuntimeWarning: Mean of empty slice.
  return (((y_pred - y_true) ** 2)).mean()
/home/ahmadnagib/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)`

Would you share the release number of TensorFlow and Keras versions that you used to run the script?, I believe using your exact versions might solve the problem.

**Comment by Mauriyin** [comment]
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0

Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0

**Comment by ahmadnagib** [comment]
> tensorboard==1.14.0
> tensorflow==1.14.0
> tensorflow-estimator==1.14.0
> 
> Keras==2.2.4
> Keras-Applications==1.0.8
> Keras-Preprocessing==1.1.0

Thanks @Mauriyin I did install the versions that you provided via a dedicated conda environment but I still get the RuntimeWarning mentioned in my previous comment. Any suggestions?

**Comment by Mauriyin** [comment]
Fixed with an update on the CQI example #12
