### ISSUE TITLE
Error: Size of memory error(16 9)

### ISSUE THREAD

**Issue by PennyXQZ** [hust-diangroup/ns3-ai#51]
Hi developer,
Thanks for you work to provider this tool. I have tried several times to install ns3-ai with ns-3-dev, ns-3.35 in ubuntu 20.04 LTS. The installation is successful but when I run a_plus_b, the error as follow is shown. Do you know why it is happen? Thanks a lot!

> (ns3-5g) ubuntu@mlmachine:~/repos/ns-3-allinone/ns-3.35/scratch/a_plus_b$ python3 run.py
> Something wrong
> Size of memory error(16 9)
> cleaning

**Comment by Mauriyin** [comment]
Hi, 
I think the shared memory wasn't successfully released from your last run. You can run the `free.sh` under the ns3-ai folder or try with a different shared memory id.

**Comment by PennyXQZ** [comment]
> Hi, I think the shared memory wasn't successfully released from your last run. You can run the `free.sh` under the ns3-ai folder or try with a different shared memory id.

Hi Mauriyin, Thanks for you reply. I try to run `freeshm.sh` but it shown:
> (ns3-5g) ubuntu@mlmachine:~/repos/ns-3-allinone/ns-3.35/contrib/ns3-ai$ sh freeshm.sh
> freeshm.sh: 2: Syntax error: "(" unexpected
how can I make freeshm.sh work successfully?

And then I changed another share memory id and it worked! And now it is stucked at `build`:
> (ns3-5g) ubuntu@mlmachine:~/repos/ns-3-allinone/ns-3.35/scratch/a_plus_b$ python3 run.py
> build
Is it normal or there is anything wrong?
Thanks again for your help!

**Comment by PennyXQZ** [comment]
> 

The freeshm.sh works now! I run it with ./freeshm.sh.

**Comment by PennyXQZ** [comment]
>
