### ISSUE TITLE
About the time sequential issue

### ISSUE THREAD

**Issue by NeonZhou** [hust-diangroup/ns3-ai#63]
Initially thanks for the contributions for this really helpful tool ns3-ai!
I have a little question about ns3-ai. How does ns3-ai keep the time sequential of the ns3 and python. I mean, when ns3 finish setting the parameters to the sharedmemory, how does it notify python that ns3's operations are done or how does python know that I can start my ML program now using the parameters derived from sharedmemory. And the same for python, how can ns3 know that python's learning is done and the result is already update to the sharedmemoy? Does this realize by some specific flag or clock?

**Comment by q240627995** [comment]
The CtrlInfoBlock is the control block of the all shared memory pool, the SharedMemoryCtrl is the control block of each shared memory, and the SharedMemoryLockable is the actual shared memory used for data exchange. In each memory block, we use version and nextVersion as the lock indicator. The synchronization for reading/writing locks and the events update are accomplished by the lock indicator. For every process that wants to access or modify the data, it will compare the version variable and the nextVersion variable. If they are the same, it means that the memory is reachable. Then it will add one to the next version atomically to lock the memory and also add one to the version after its operation to the memory to unlock the memory. Besides the version of the memory acts as the signal to tell different processes the current state of the memory block, which provides different methods to synchronize.

**Comment by NeonZhou** [comment]
> The CtrlInfoBlock is the control block of the all shared memory pool, the SharedMemoryCtrl is the control block of each shared memory, and the SharedMemoryLockable is the actual shared memory used for data exchange. In each memory block, we use version and nextVersion as the lock indicator. The synchronization for reading/writing locks and the events update are accomplished by the lock indicator. For every process that wants to access or modify the data, it will compare the version variable and the nextVersion variable. If they are the same, it means that the memory is reachable. Then it will add one to the next version atomically to lock the memory and also add one to the version after its operation to the memory to unlock the memory. Besides the version of the memory acts as the signal to tell different processes the current state of the memory block, which provides different methods to synchronize.

@q240627995 
Thank you for your help!
So in ns3-ai, pyhton and ns3 are not running parallelly but sequentially? When one side is done, it changed the version and next version variables and just go ahead. And use version, mod and rst variables(even for ns-3 and odd for python) to make sure next time it will be the other side to access the sharedmemory.
I'm not sure if my understanding is right, hopefully I can get your correction. Thank a lot!

**Comment by q240627995** [comment]
> @q240627995 Thank you for your help! So in ns3-ai, pyhton and ns3 are not running parallelly but sequentially? When one side is done, it changed the version and next version variables and just go ahead. And use version, mod and rst variables(even for ns-3 and odd for python) to make sure next time it will be the other side to access the sharedmemory. I'm not sure if my understanding is right, hopefully I can get your correction. Thank a lot!

I think it's what you said about alternate running. It's speculated that there will be a sleep lock when obtaining shared memory. The specific thing to see is his code implementation (I'm too lazy to watch, just use it)

**Comment by NeonZhou** [comment]
Oh I see, thank you for your time!
