### ISSUE TITLE
Using NS3-AI module in NS-3 3.36 release (or greater)

### ISSUE THREAD

**Issue by inaki524** [hust-diangroup/ns3-ai#66]
Hi all the devs of NS3-AI module. 

Currently I am using NS3-AI for a project, operating in NS-3 3.35 release. I would like to migrate to the new 3.36 release due to several reasons. However, this new version employs **CMake instead of Waf as the NS-3 build system,** as stated here https://www.nsnam.org/releases/ns-3-36/. This is a problem due to the fact that most recent stable release of NS3-AI (v1.1.0) **still uses Waf as build system**. I would like to know if there are any plans in the community to update NS3-AI so that it is compatible with this new NS-3 build system in the near future.

P.S. having a look at the branches in the repository, I have found a branch called "cmake" with a couple of commits. Is this branch related to this kind of update? Is this change in progress or can be already used?

Thanks in advance for your answer and thank you again for your work and dedication to this useful project.

**Comment by Mauriyin** [comment]
Hi,
Yes, the CMake branch should be ready to use but only for compiling the ns3-ai module. We haven't got all the examples and documents ready, so haven't released them yet.
